### PR TITLE
remove [] to support fields[] on post method

### PR DESCRIPTION
**Pull request by quydox**
Hello team,

I have just created pull request to allow post array of fields

Detail on this issue https://github.com/fastify/fastify-multipart/issues/120#issuecomment-851791002

Can you review it?

Thanks,

### CODE REVIEW

**Comment by mcollina** [comment]
Thanks for your contribution! Would you mind:

* [ ] make this behavior optional
* [ ] add tests to cover this feature

Thanks!

**Comment by quydox** [comment]
> Thanks for your contribution! Would you mind:
> 
> * [ ]  make this behavior optional
> * [ ]  add tests to cover this feature
> 
> Thanks!

Thanks bro,

1. You mean add it as optional?
2. write a test file to procedure this feature?

**Comment by mcollina** [comment]
Yes exactly

**Comment by quydox** [comment]
Okay, let me do it

**Comment by quydox** [comment]
Hello I have just add option, here is the test repo

https://github.com/quydox/fastify-multipart-test

Can you check it bro?

Thanks,

**Comment by mcollina** [comment]
This needs a unit test in this repo.

**Comment by quydox** [comment]
Hi, this repo means your repo or mine :D?

**Comment by mcollina** [comment]
It should be included in this pull request.

**Comment by mcollina** [comment]
Closed for no activity, feel free to reopen if you are still interested in pursuing this

**Pull request closed without merging**
