### PR TITLE
Export interface BodyEntry

### PR DESCRIPTION
**Pull request by andresribeiro**
Now the `BodyEntry` interface is being exported

#### Checklist

- [ x ] run `npm run test` and `npm run benchmark`
- [ x ] tests and/or benchmarks are included
- [ x ] documentation is changed or added
- [ x ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
Can you add a test in https://github.com/fastify/fastify-multipart/blob/master/test/index.test-d.ts?

**Comment by andresribeiro** [comment]
Hey, @mcollina! Thanks for your quick reply. Unfortunately, I have no experience with testing 😕

**Comment by mcollina** [comment]
You would need to add the import in https://github.com/fastify/fastify-multipart/blob/master/test/index.test-d.ts#L3 and use that interface in that file.

**Comment by kibertoad** [comment]
@andresribeiro Do you need any additional help?

**Comment by andresribeiro** [comment]
> @andresribeiro Do you need any additional help?

Actually yes 😅

**Pull request closed without merging**
