### PR TITLE
Remove legacy addToBody and callback API

### LINKED ISSUE #202: increase code coverage
as titled

### LINKED ISSUE #289: migrate out of deprecated API.
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.x.x

### Plugin version

_No response_

### Node.js version

14.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

Migrate out of deprecated API.

https://github.com/fastify/fastify-multipart/blob/37165757947857cd8b3977ba362c4536fd2d837e/index.js#L36-L44

`request.multipart` is actually deprecated, it should not be used inside this plugin.

Reported by Jones on Discord Server.

### Steps to Reproduce

Register the plugin with `addToBody`.
```js
fastify.register(multipart, {
  addToBody: true,
});
```

### Expected Behavior

No deprecation warning.

### PR DESCRIPTION
**Pull request by gurgunday**
I saw #464 and got excited about this plugin again 🤠

We can start by removing the `addToBody` option that has been deprecated (or at least undocumented) for [nearly 2 years](https://github.com/fastify/fastify-multipart/issues/289) now

AFAICT, this closes #289, closes #202 (line coverage gets to 100%), and maybe even #435 (by removing the related part of the code)

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Eomm — COMMENTED** [review]
Isn't it the beginner feature?

https://github.com/fastify/fastify-multipart/issues/464#issuecomment-1650906349

**Comment by gurgunday** [comment]
> Isn't it the beginner feature?
> 
> [#464 (comment)](https://github.com/fastify/fastify-multipart/issues/464#issuecomment-1650906349)

That would be attachFieldsToBody: true or even better attachFieldsToBody: “keyValues”

https://github.com/fastify/fastify-multipart#parse-all-fields-and-assign-them-to-the-body

**Review by mcollina — APPROVED** [review]
lgtm

I think we could start a `next` branch here

**Comment by gurgunday** [comment]
Can we merge this?

`addToBody` definitely needs to go and I want to start working on the next version without having to fight with conflicts in my other PRs

**Comment by gurgunday** [comment]
CC @climba03003

**Review by Uzlopak — APPROVED** [review]
LGTM

**Pull request merged**
