### PR TITLE
Return buffers directly when `attachFieldsToBody` is set to `'keyValues'`

### LINKED ISSUE #447: onFile hook doesn't work on files array field with (attachFieldsToBody: "keyValues")
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.17.0

### Plugin version

7.6.0

### Node.js version

18.15.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.2 (Ventura)

### Description

I want to attach files to my body which also contains other data like strings and booleans.

I used the **attachFieldsToBody: "keyValues"** option, and it seems to work.

**There are however two problems:**

1) the file is attached to the body with the default value buffer.toString(). Here it doesn't appear to convert to a base64 or utf-8 string due to the presence of unknown characters. So it's impossible to restore the buffer and therefore the file from that string. I managed to get around this by using the **onFile hook** which allowed me to return a correct base64 string.

```
onFile: async function (part) {
  const buff = await part.toBuffer();
  const base64_file = buff.toString("base64");
  const type = await fileTypeFromBuffer(buff);
  part.value = {
      file: base64_file,
      type: type,
  };
}
```

2) The problem now is that if I pass more than one file into the same form field, I get returned an array of strings that are not "processed" by the "onFile" hook and are therefore unusable. it's like the onFile hook only works if there is a single file in a specific key of the body, if it's an array it doesn't get executed.

Can anyone come and help me?

### Steps to Reproduce

**1) package.json**

```
{
  "name": "fastifyplayground",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@fastify/multipart": "^7.6.0",
    "fastify": "^4.17.0",
    "file-type": "^18.5.0",
    "mime-types": "^2.1.35"
  },
  "type": "module"
}
```

**2) index.js**

```
import Fastify from "fastify";
import { fileTypeFromBuffer } from "file-type";

// Require the framework and instantiate it
const fastify = Fastify({
    logger: true,
});

// register multipart plugin
fastify.register(import("@fastify/multipart"), {
    attachFieldsToBody: "keyValues",
    limits: {
        fileSize: 1048576, // 1MB
    },
    onFile: async function (part) {
        const buff = await part.toBuffer();
        const base64_file = buff.toString("base64");
        const type = await fileTypeFromBuffer(buff);
        part.value = {
            file: base64_file,
            type: type,
        };
    },
});

// Declare a route
fastify.route({
    method: "POST",
    url: "/upload",
    handler: async (request, reply) => {
        // get body values
        const test = request.body.test;
        const image = request.body.image;

        // response
        return {
            test: test,
            image: image,
        };
    },
});

// Run the server!
const start = async () => {
    try {
        await fastify.listen({ port: 3000 });
    } catch (err) {
        fastify.log.error(err);
        process.exit(1);
    }
};
start();

```

### Expected Behavior

_No response_

### PR DESCRIPTION
**Pull request by gurgunday**
Carries over the work of https://github.com/fastify/fastify-multipart/pull/456

Closes #447

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by gurgunday** [comment]
I will edit the documentation as well

**Review by mcollina — APPROVED** [review]
lgtm

This is a semver-major change

Given the discussion on #464, should we land both this and #465 and release? Or wait for more changes?

**Comment by gurgunday** [comment]
> lgtm
> 
> This is a semver-major change
> 
> Given the discussion on #464, should we land both this and #465 and release? Or wait for more changes?

In my opinion it would depend on how long the rewrite/refactor would take to complete

I'm currently eyeing giving it a shot, but haven't even finished properly reading the code

**Comment by gurgunday** [comment]
I will do some very minor refactoring here to improve the consistency of the code

**Comment by climba03003** [comment]
> Or wait for more changes?

Not in a hurry.
I will wait for more at this stage since it is expected to contain many breaking changes.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
@climba03003 you ok for this to land on `next`?

**Review by climba03003 — APPROVED** [review]
Yes

**Pull request merged**
