### PR TITLE
When options.attachFieldsToBody is set to "keyValues" do not stringify buffer, but return the Buffer

### PR DESCRIPTION
**Pull request by alifuma92**
The details that led to the creation of this pull request are described in this issue.

https://github.com/fastify/fastify-multipart/issues/447

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
Thanks for opening a PR! Can you please add a unit test?

**Comment by gurgunday** [comment]
Hey @alifuma92, thank you very much for the PR! I would really appreciate it if we could get this merged, could you please add a unit test when you have the time? ❤️

**Comment by andersonjoseph** [comment]
btw this change was previously discussed [here](https://github.com/fastify/fastify-multipart/pull/348/files/8eaf5f303ea59be087b5dbeb62b40b42894c9c8e#r890340097)

**Comment by gurgunday** [comment]
I couldn’t comment on that discussion, but base64 encoding simply breaks [sharp](https://github.com/lovell/sharp) image processing for me even if I reconvert it back to a buffer

Moreover, not sure why the in-memory buffer is seen as such a bad idea in general **when** you can set a fileSize limit along with a custom error handler to be safe

**Comment by mcollina** [comment]
@gurgunday I don't think this is covering Base64 encoding. Or maybe I misunderstood this PR

**Comment by gurgunday** [comment]
> I don't think this is covering Base64 encoding

Yeah, for some reason I wanted to comment about that [discussion](https://github.com/fastify/fastify-multipart/pull/348/files/8eaf5f303ea59be087b5dbeb62b40b42894c9c8e#r890340097) from here where they discussed using `base64` encoding to stringify the buffer

My issue is that, whatever the type of encoding, once the buffer is stringified, `sharp` won't accept that input even if it's reconverted back, or at least that's what happened to me, which is why I'd like it to just return the buffer instead of doing any conversions

**Comment by mcollina** [comment]
That's what this does, right?

Would you like to take over this work @gurgunday ?

**Comment by gurgunday** [comment]
I'd love to 😁

**Comment by mcollina** [comment]
go for it!

**Comment by savvykir** [comment]
Any updates in here?

**Pull request closed without merging**
