### PR TITLE
fix: make sure the handler resolves in all cases

### LINKED ISSUE #497: Request hangs if an error is thrown while processing a file
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.24.3

### Plugin version

8.0.0

### Node.js version

18.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

The `for..await of` promise doesn't get fulfilled (or rejected) if an error is throw when processing a single file. For example, in the following code, the line "done processing all files" doesn't get logged.

```js
const files = await request.files();

for await (const { file, filename } of files) {
  console.log("start processing file", filename);

  try {
    const storage = new Writable({
      write(chunk, encoding, callback) {
        // trigger error:
        callback(new Error("write error"));
      },
    });

    await pipeline(file, storage);
  } catch (error) {
    console.log("caught error while processing file", filename, error);
    // note that the error isn't rethrown here, so this error is now handled
    // and processing should proceed
  }

  console.log("done processing file", filename);
}

console.log("done processing all files");

return reply.send(files);
```

Also, if the `try..catch` is removed, everything freezes after "start processing file".

On a separate/related note, is it possible to use `@fastify/multipart` but with the stream-based api instead of the generators? 

### Steps to Reproduce

Repro: https://github.com/joelmukuthu/fastify-multipart-hanging-bug.

### Expected Behavior

That the request would not hang. If the error is not handled properly (e.g. if there's no `try..catch` in the example above), I'd expect that the request fails with an error.

### PR DESCRIPTION
**Pull request by gurgunday**
partially fixes #497

The request still freezes without the `try catch` and I'm not sure how we could remedy that

### CODE REVIEW

**Review by climba03003 — COMMENTED** [review]
Seems like it was a wrong choice to use `while` for generator.
I knew it will cause problem somehow, that's why I prefer to use [`AsyncIterator`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncIterator)

Something similar can be done by,
https://github.com/kaka-ng/fastify-plugins/blob/main/packages/multipart/lib/adapter/busboy.ts#L116-L156

**Comment by gurgunday** [comment]
I don't get an error on node 16, 18, 20, or 21

What is up with 14?..

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by gurgunday** [comment]
Alright, I'll simplify (I tried to go overboard so that it resolves in node 14 but it just won't catch the error...)

Should we merge like this or should I merge to next?

**Comment by Uzlopak** [comment]
@gurgunday 

Can you shortly describe why it fails on 14?

**Comment by gurgunday** [comment]
I can't for the moment 🤣

Essentially, the test I added doesn't pass on node 14, and it needs investigation

**Comment by gurgunday** [comment]
Note that it's not because of what this PR does, it is because the PR doesn't fix the issue on node 14

**Comment by gurgunday** [comment]
Seems like on node 14 request.raw.on('error') is not firing... anyone has a guess on why that might be? Was it added recently?

**Comment by mcollina** [comment]
I think the destroy logic in v14 is _really different_.

**Review by mcollina — APPROVED** [review]
lgtm

**Review by climba03003 — APPROVED** [review]

**Review by Uzlopak — APPROVED** [review]
RSLGTM

**Comment by gurgunday** [comment]
Will cut a patch

**Comment by mcollina** [comment]
a patch? This is in the next branch? Is that ready to ship?

**Comment by gurgunday** [comment]
> a patch? This is in the next branch? Is that ready to ship?

Yeah, forgot for a second

It's not ready IMO, we can wait till v5 since maybe I'll be able to do the major rewrite... unless someone needs this patch ASAP

**Comment by joelmukuthu** [comment]
Thanks @gurgunday (and reviewers) for working on this fix. I understand that there are some issues with getting this released due to node 14, but is there any chance to get this released in a bug-fix release? Or do you have a rough timeline for the v5 release?

**Comment by gurgunday** [comment]
@mcollina, should I add a skip to the test and backport it to main? Or would you prefer releasing next?

**Pull request merged**
