### PR TITLE
chore tap 15

### PR DESCRIPTION
**Pull request by Eomm**
This is an automatic PR created with [massive-wax](https://github.com/Eomm/massive-wax)!

### CODE REVIEW

**Comment by mcollina** [comment]
CI fails

**Comment by zekth** [comment]
FIxed the flag but cannot reproduce the test failing on my current machine.

**Comment by mcollina** [comment]
You need to set `check-coverage: false` in `.taprc`

**Comment by Eomm** [comment]
There is a test skipped on windows that I can't get pass :/

**Comment by mcollina** [comment]
> There is a test skipped on windows that I can't get pass :/

I'm lost. Is this failing elsewhere? Are you trying to get this test to pass on Windows?

**Comment by zekth** [comment]
@mcollina i fixed the test. It seems that `tap` has changed its api for `t.match` which was matching a `Buffer` as an `Array`. I made a slight change to the test, it might not be pretty as the match pattern but i haven't found anything in the doc to match it properly

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
