### PR TITLE
fix(typing): Allows all busboy options on plugin registration

### PR DESCRIPTION
**Pull request by johaven**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

**Fix**
Options like `preservePath` are not known

### CODE REVIEW

**Review by gurgunday — CHANGES_REQUESTED** [review]
Thanks for the PR

Can you add a test using `tsd`?

**Comment by johaven** [comment]
> Can you add a test using `tsd`?

done :)

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Here is a PR that fixes linting https://github.com/fastify/fastify-multipart/pull/538

**Comment by mcollina** [comment]
Can you please rebase your PR?

**Comment by mcollina** [comment]
@gurgunday ptal

**Review by gurgunday — APPROVED** [review]

**Pull request merged**
