### PR TITLE
chore(deps-dev): replace eslint-plugin-node with eslint-plugin-n

### PR DESCRIPTION
**Pull request by Fdawgs**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Uzlopak — APPROVED** [review]
LGTM

**Comment by climba03003** [comment]
For `eslint-config-standard-with-typescript`, the below is what it required.
```
"@typescript-eslint/eslint-plugin": "^5.30.7",
"@typescript-eslint/parser": "5.30.7",
"eslint": "^8.20.0",
"eslint-config-standard-with-typescript": "^22.0.0",
"eslint-plugin-import": "^2.26.0",
"eslint-plugin-n": "^15.2.4",
"eslint-plugin-promise": "^6.0.0",
```

**Comment by Fdawgs** [comment]
> For `eslint-config-standard-with-typescript`, the below is what it required.
> 
> ```
> "@typescript-eslint/eslint-plugin": "^5.30.7",
> "@typescript-eslint/parser": "5.30.7",
> "eslint": "^8.20.0",
> "eslint-config-standard-with-typescript": "^22.0.0",
> "eslint-plugin-import": "^2.26.0",
> "eslint-plugin-n": "^15.2.4",
> "eslint-plugin-promise": "^6.0.0",
> ```

You've lost me there @climba03003, are you saying I should get rid of the other configs and plugins?

**Comment by climba03003** [comment]
> You've lost me there @climba03003, are you saying I should get rid of the other configs and plugins?

Yes, basically it should remove all those packages. Since it didn't use in anywhere.

**Comment by Fdawgs** [comment]
> > You've lost me there @climba03003, are you saying I should get rid of the other configs and plugins?
> 
> Yes, basically it should remove all those packages. Since it didn't use in anywhere.

Cool beans, done in https://github.com/fastify/fastify-multipart/pull/374/commits/047887efd34636592103b34a0f755bbe33a3bb79

**Review by climba03003 — APPROVED** [review]

**Pull request merged**
