### PR TITLE
add concat-stream to devDependencies

### PR DESCRIPTION
**Pull request by Uzlopak**
Currently, rimraf and concat-stream are imported because they are dependencies of other packages. This PR adds them explicitly.

### CODE REVIEW

**Review by climba03003 — APPROVED** [review]
LGTM.

Can we replace `rimraf` with `fs.rmdirSync`

**Comment by kibertoad** [comment]
@climba03003 I doubt it, if they are transitive dependencies, unless we send PRs upstream.
@Uzlopak do you know which packages depend on rimraf?

**Comment by climba03003** [comment]
> I doubt it, if they are transitive dependencies, unless we send PRs upstream.

I means it is added in `devDepenencies` because we directly using it.
If we remove the direct usage, then it can be removed in `devDepenencies`.

**Comment by Uzlopak** [comment]
@kibertoad 
tap requires rimraf, as it is a dependency of nyc.

**Comment by climba03003** [comment]
> What do you prefer?

`await fs.promises.rm(tmpdir, { recursive: true, force: true })`

Since we always test against the latest version of node (inside that major).
If all of them provide `fs.promises.rm`, then no need a extra check for it.

**Review by climba03003 — APPROVED** [review]
Thanks

**Review by kibertoad — APPROVED** [review]

**Pull request merged**
