### PR TITLE
remove dependency readable-stream

### PR DESCRIPTION
**Pull request by Uzlopak**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by kibertoad — APPROVED** [review]

**Comment by Fdawgs** [comment]
Quick one, why does it need replacing?

**Comment by kibertoad** [comment]
@Fdawgs Isn't it generally preferable to use native solutions over custom libraries?

**Comment by Uzlopak** [comment]
I am actually trying to figure out why the tests are flaky. I have the bad feeling that it has something to do with how busboy works and the events it is calling. Something like finish instead of close. Unfortunately I can not reproduce the issues on my local machine. Something is quite odd.

**Comment by Fdawgs** [comment]
> @Fdawgs Isn't it generally preferable to use native solutions over custom libraries?

Of course! Sorry, had a brain fart and forgot stream was native. 😂

**Comment by Eomm** [comment]
>  Unfortunately I can not reproduce the issues on my local machine.

Same error as the CI for me with node v18.6.0

**Comment by Uzlopak** [comment]
Yes on node 18.8.0 it breaks. On node 16.17.0 it works.

So there is an issue when running it on node 18 and I have no clue.

**Comment by kibertoad** [comment]
Streams notoriously change all the time across Node versions :D

**Comment by climba03003** [comment]
> Isn't it generally preferable to use native solutions over custom libraries?

@kibertoad 
For `stream`, NO. It prefer to use `readable-stream` for library. 
If it is self project and tagged to single node version, then native no is better.

**Pull request closed without merging**
