### PR TITLE
Remove unnecessary await keywords from documentations, tests and examples

### PR DESCRIPTION
**Pull request by maxloh**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

This pull request remove unnecessary await keyword from documentations.

Related: https://github.com/fastify/fastify-multipart/pull/233#issuecomment-841374036, https://github.com/fastify/fastify-multipart/pull/233#issuecomment-841638187

#### Strings to check

- [x] `await req.files`
- [x] `await req.parts`
- [x] `await req.body.`

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
cc @StarpTech

**Comment by StarpTech** [comment]
@maxloh could you also remove it from the tests and examples?

**Comment by maxloh** [comment]
> @maxloh could you also remove it from the tests and examples?

OK. Should I open another pull request for that?

**Comment by StarpTech** [comment]
I'd put it all together.

**Comment by maxloh** [comment]
> I'd put it all together.

Ok. Give me 2 to 3 days for that.

**Comment by StarpTech** [comment]
Take your time. It's not urgent.

**Comment by maxloh** [comment]
The pull request is ready to review.

Note: I also make the following two code snippets more consistent.

https://github.com/fastify/fastify-multipart/blob/0825f0f54d9430ff0da50078cdbd9f7778b1ab5e/README.md#L181-L213

**Review by StarpTech — APPROVED** [review]
lgtm, thank you!

**Pull request merged**
